server:
  port: 8674
  jwt.secret: Crayon

spring:
  application:
    name: auth-server
    
eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
    instance-id: ${eureka.instance.hostname}:${server.port}
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka/