server:
  port: 8761
  servlet:    context-path: /service-registry/
eureka:
  client:
    fetch-registry: false
    register-with-eureka: false
  server:
    enable-self-preservation: true
    eviction-interval-timer-in-ms: 5000
spring:
  application:
    name: service-registry

