server:
  port: 8673
  jwt.secret: Crayon

spring:
  cloud:
    gateway:
      routes:

      # login url
      - id: auth-login
        uri: lb://auth-server/login
        predicates:
          - Path=/login/**

      # app web layer
      - id: app-web
        uri: lb://app-web
        predicates:
          - Path=/app/**
        filters:
          - JWTFilter=RSA256,HS256
          - RemoveResponseHeader=X-Powered-By
      # admin web layer
      - id: admin-web
        uri: lb://admin-web
        predicates:
          - Path=/admin/**
        filters:
          - JWTFilter=RSA256,HS256
          - RemoveResponseHeader=X-Powered-By

